### ISSUE TITLE
部分误伤反馈

### ISSUE THREAD

**Issue by lychichem** [523860169/list#2]
https://www.bilibili.com/account/history 这个页面需要xhr请求https://data.bilibili.com/log/web?0000151514205755704https%3A%2F%2Fwww.bilibili.com%2Faccount%2Fhistory (之后涉及个人信息省略）这样的url，而标题这条规则会误伤，表现为历史记录页面白板。

**Comment by lychichem** [comment]
js.t.sinajs.cn这条规则会误伤微博页面的大量脚本和样式，例如表情面板的样式，鼠标悬停在“查看图片”上时的弹层，鼠标悬停在微博ID上时的弹出式信息卡，右下角的“回到顶部”按钮等

**Comment by 523860169** [comment]
第一条已经修复了，第二条没发现这个规则，唯一一个相关的还是白名单，所以，应该是其他规则吧?

**Comment by lychichem** [comment]
@523860169 我觉得这个规则应该是||sinajs.cn/open/analytics/ ，但是很奇怪的是这个不是应该只对sinajs开头的生效而不应该对js.t.sinajs.cn这种生效的么？难道说edge的ublock的理解方式和其他浏览器的不同？规则的话我只有你这一个规则，所以不存在其他规则的情况。

**Comment by 523860169** [comment]
@@||sinajs.cn/open/analytics/js/suda.js$domain=weibo.com|~widget.weibo.com
默认不是有这个白名单吗？直接搜索sinajs.cn/open/analytics，也是只能搜到这两条规则。
我这边也没法复现你说的这几个问题，可能你需要提供下浏览器版本，过滤扩展，因为我用火狐+pan和chrome+abp都没有重现

**Comment by lychichem** [comment]
@523860169 怎么说呢……我这里也并不是100%重现，只是不直接把这个加到自定义白名单的话就大概率加载不出来……我估计可能和edge本身的技能或者ublock edge本身的机能有关。
至于浏览器，这边是MS Edge 41.16299.15.0+ublock 1.14.23的组合

**Comment by 523860169** [comment]
试了一下，应该是edge的ublock对abp里的~规则支持不好，edge+ablock就没问题，chrome+ublock也没问题

**Comment by lychichem** [comment]
@523860169 行了，逼到uBO的作者改core了，我测过问题已经修好了，现在就坐等uBO-Edge的作者merge并推送了

**Comment by 523860169** [comment]
好的，不过我感觉edge其实还是放弃的好，需要IE的网站还是需要IE，不需要IE的，也轮不到edge
