### ISSUE TITLE
贴吧帖子列表页右侧浮动导航条被屏蔽

### ISSUE THREAD

**Issue by lychichem** [523860169/list#4]
在帖子内没有问题,在帖子列表页是有问题的

**Comment by Firef0x** [comment]
@lychichem ，您好！

在 https://github.com/523860169/list/blob/master/README.md#包含 中提到：

> ad.txt：整合iFL（贴吧清爽规则）、cjx和chinalist规则，以及补充的一些规则；

我觉得是 `iFL` 的规则太强力了，也许您应该向 [@神殤￠無月](http://tieba.baidu.com/home/main?un=%C9%F1%9A%91%A1%E9%9Fo%D4%C2) 的项目 [自用过滤规则 ](https://code.csdn.net/i_square/i/tree/master) 提出 Issue 比较好。

此致！ :bow:

**Comment by lychichem** [comment]
我没有那个网站的账号，另外iFL如果要动的话工程量太大，现有filter就对iFL做了一次修改，所以如果直接对原始列表提issue的工程量可想而知

 

发件人: Fernando Gilberto Pereira da Silva [mailto:notifications@github.com] 
发送时间: 2015年1月20日 15:01
收件人: 523860169/list
抄送: lychichem
主题: Re: [list] 贴吧帖子列表页右侧浮动导航条被屏蔽 (#4)

 

@lychichem <https://github.com/lychichem>  ，您好！

在 https://github.com/523860169/list/blob/master/README.md# <https://github.com/523860169/list/blob/master/README.md#%E5%8C%85%E5%90%AB> 包含 中提到：

ad.txt：整合iFL（贴吧清爽规则）、cjx和chinalist规则，以及补充的一些规则；

我觉得是 iFL 的规则太强力了，也许您应该向 @ <http://tieba.baidu.com/home/main?un=%C9%F1%9A%91%A1%E9%9Fo%D4%C2> 神殤￠無月 的项目  <https://code.csdn.net/i_square/i/tree/master> 自用过滤规则 提出 Issue 比较好。

此致！

**Comment by 523860169** [comment]
@Firef0x ，你好。
ad.txt自从上次对iFL规则进行修改后就已经不再对iFL规则进行Fork操作，原因是避免冲突，和降低维护难度，谢谢支持。

**Comment by 523860169** [comment]
反馈的问题已解决，对本issue做关闭处理，谢谢支持。
